# permissions for end users to edit foos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: chapter-7
    app.kubernetes.io/managed-by: kustomize
  name: samplecontroller-foo-editor-role
rules:
- apiGroups:
  - samplecontroller.io
  resources:
  - foos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplecontroller.io
  resources:
  - foos/status
  verbs:
  - get
