apiVersion: samplecontroller.io/v1beta
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: chapter-7
    app.kubernetes.io/managed-by: kustomize
  name: foo-sample
spec:
  # TODO(user): Add fields here
