apiVersion: foo.poko.io/v1alpha
kind: Foo
metadata:
  labels:
    app.kubernetes.io/name: foo-controller-operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: foo-sample
spec:
  # TODO(user): Add fields here
